### ISSUE TITLE
PRs are missing

### ISSUE THREAD

**Issue by ruslan-palahin** [TheWingedShake/fruitnija#4]
@TheWingedShake Hi, please can you create a PR into master for each feature, please? Thanks in advance.

Sword animation updated link https://drive.google.com/open?id=1qD-ARarkCPub4eLfYNJkoRHAG-AUcZKU

**Comment by TheWingedShake** [comment]
> 
> 
> @TheWingedShake Hi, please can you create a PR into master for each feature, please? Thanks in advance.
> 
> Sword animation updated link https://drive.google.com/open?id=1qD-ARarkCPub4eLfYNJkoRHAG-AUcZKU

Hi.
I've created 2 pull requests. After review i will create new one pull request with new feature(it depends on code from previews PRs).
